# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_transectizer.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_transectizer(object):
    def setupUi(self, transectizer):
        transectizer.setObjectName(_fromUtf8("transectizer"))
        transectizer.setWindowModality(QtCore.Qt.WindowModal)
        transectizer.setEnabled(True)
        transectizer.resize(273, 603)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(transectizer.sizePolicy().hasHeightForWidth())
        transectizer.setSizePolicy(sizePolicy)
        transectizer.setMaximumSize(QtCore.QSize(273, 603))
        font = QtGui.QFont()
        font.setPointSize(8)
        transectizer.setFont(font)
        transectizer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        transectizer.setModal(True)
        self.groupBox = QtGui.QGroupBox(transectizer)
        self.groupBox.setGeometry(QtCore.QRect(0, 410, 271, 171))
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 257, 109))
        self.layoutWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.namingLayout = QtGui.QGridLayout(self.layoutWidget)
        self.namingLayout.setMargin(0)
        self.namingLayout.setObjectName(_fromUtf8("namingLayout"))
        self.surveyName = QtGui.QLineEdit(self.layoutWidget)
        self.surveyName.setAcceptDrops(False)
        self.surveyName.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.surveyName.setMaxLength(20)
        self.surveyName.setObjectName(_fromUtf8("surveyName"))
        self.namingLayout.addWidget(self.surveyName, 2, 0, 1, 1)
        self.stnPreLabel = QtGui.QLabel(self.layoutWidget)
        self.stnPreLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stnPreLabel.setObjectName(_fromUtf8("stnPreLabel"))
        self.namingLayout.addWidget(self.stnPreLabel, 3, 0, 1, 1)
        self.iniNumLabel = QtGui.QLabel(self.layoutWidget)
        self.iniNumLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.iniNumLabel.setObjectName(_fromUtf8("iniNumLabel"))
        self.namingLayout.addWidget(self.iniNumLabel, 3, 1, 1, 1)
        self.stationPrefix = QtGui.QLineEdit(self.layoutWidget)
        self.stationPrefix.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stationPrefix.setMaxLength(5)
        self.stationPrefix.setObjectName(_fromUtf8("stationPrefix"))
        self.namingLayout.addWidget(self.stationPrefix, 4, 0, 1, 1)
        self.autoNameCheck = QtGui.QCheckBox(self.layoutWidget)
        self.autoNameCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.autoNameCheck.setChecked(True)
        self.autoNameCheck.setObjectName(_fromUtf8("autoNameCheck"))
        self.namingLayout.addWidget(self.autoNameCheck, 0, 0, 1, 2)
        self.initialStationNumber = QtGui.QSpinBox(self.layoutWidget)
        self.initialStationNumber.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.initialStationNumber.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.initialStationNumber.setAccelerated(True)
        self.initialStationNumber.setProperty("value", 1)
        self.initialStationNumber.setObjectName(_fromUtf8("initialStationNumber"))
        self.namingLayout.addWidget(self.initialStationNumber, 4, 1, 1, 1)
        self.srvNameLabel = QtGui.QLabel(self.layoutWidget)
        self.srvNameLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.srvNameLabel.setObjectName(_fromUtf8("srvNameLabel"))
        self.namingLayout.addWidget(self.srvNameLabel, 1, 0, 1, 2)
        self.newTransectButton = QtGui.QPushButton(self.groupBox)
        self.newTransectButton.setGeometry(QtCore.QRect(30, 140, 211, 20))
        self.newTransectButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.newTransectButton.setAutoDefault(False)
        self.newTransectButton.setObjectName(_fromUtf8("newTransectButton"))
        self.groupBox_2 = QtGui.QGroupBox(transectizer)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 271, 280))
        self.groupBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 170, 250, 102))
        self.layoutWidget1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.unitsCombo = QtGui.QComboBox(self.layoutWidget1)
        self.unitsCombo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.unitsCombo.setAutoFillBackground(False)
        self.unitsCombo.setStyleSheet(_fromUtf8("font: 8pt \"Sans Serif\";"))
        self.unitsCombo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.unitsCombo.setEditable(True)
        self.unitsCombo.setFrame(True)
        self.unitsCombo.setObjectName(_fromUtf8("unitsCombo"))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.unitsCombo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.unitsCombo, 2, 1, 1, 1)
        self.dstBtwnStLabel = QtGui.QLabel(self.layoutWidget1)
        self.dstBtwnStLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dstBtwnStLabel.setObjectName(_fromUtf8("dstBtwnStLabel"))
        self.gridLayout_3.addWidget(self.dstBtwnStLabel, 1, 0, 1, 1)
        self.dstBtwnStLabel_2 = QtGui.QLabel(self.layoutWidget1)
        self.dstBtwnStLabel_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dstBtwnStLabel_2.setObjectName(_fromUtf8("dstBtwnStLabel_2"))
        self.gridLayout_3.addWidget(self.dstBtwnStLabel_2, 2, 0, 1, 1)
        self.numberOfStationsLabel = QtGui.QLabel(self.layoutWidget1)
        self.numberOfStationsLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.numberOfStationsLabel.setObjectName(_fromUtf8("numberOfStationsLabel"))
        self.gridLayout_3.addWidget(self.numberOfStationsLabel, 3, 0, 1, 1)
        self.bearingLabel = QtGui.QLabel(self.layoutWidget1)
        self.bearingLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.bearingLabel.setObjectName(_fromUtf8("bearingLabel"))
        self.gridLayout_3.addWidget(self.bearingLabel, 0, 0, 1, 1)
        self.numberOfStations = QtGui.QSpinBox(self.layoutWidget1)
        self.numberOfStations.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.numberOfStations.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.numberOfStations.setMinimum(1)
        self.numberOfStations.setMaximum(999)
        self.numberOfStations.setProperty("value", 1)
        self.numberOfStations.setObjectName(_fromUtf8("numberOfStations"))
        self.gridLayout_3.addWidget(self.numberOfStations, 3, 1, 1, 1)
        self.dstBtwnStations = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.dstBtwnStations.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dstBtwnStations.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dstBtwnStations.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.dstBtwnStations.setDecimals(3)
        self.dstBtwnStations.setMaximum(999999.99)
        self.dstBtwnStations.setProperty("value", 1.0)
        self.dstBtwnStations.setObjectName(_fromUtf8("dstBtwnStations"))
        self.gridLayout_3.addWidget(self.dstBtwnStations, 1, 1, 1, 1)
        self.bearing = QtGui.QSpinBox(self.layoutWidget1)
        self.bearing.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bearing.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.bearing.setMaximum(359)
        self.bearing.setObjectName(_fromUtf8("bearing"))
        self.gridLayout_3.addWidget(self.bearing, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 50, 226, 111))
        self.layoutWidget2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.startLonLabel = QtGui.QLabel(self.layoutWidget2)
        self.startLonLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startLonLabel.setObjectName(_fromUtf8("startLonLabel"))
        self.gridLayout.addWidget(self.startLonLabel, 1, 0, 1, 1)
        self.finalLonLabel = QtGui.QLabel(self.layoutWidget2)
        self.finalLonLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.finalLonLabel.setObjectName(_fromUtf8("finalLonLabel"))
        self.gridLayout.addWidget(self.finalLonLabel, 3, 0, 1, 1)
        self.StartLatLAbel = QtGui.QLabel(self.layoutWidget2)
        self.StartLatLAbel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.StartLatLAbel.setObjectName(_fromUtf8("StartLatLAbel"))
        self.gridLayout.addWidget(self.StartLatLAbel, 0, 0, 1, 1)
        self.finalLatLabel = QtGui.QLabel(self.layoutWidget2)
        self.finalLatLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.finalLatLabel.setObjectName(_fromUtf8("finalLatLabel"))
        self.gridLayout.addWidget(self.finalLatLabel, 2, 0, 1, 1)
        self.startLat = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.startLat.setMouseTracking(False)
        self.startLat.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.startLat.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startLat.setKeyboardTracking(True)
        self.startLat.setDecimals(6)
        self.startLat.setMinimum(-99999999.0)
        self.startLat.setMaximum(99999999.0)
        self.startLat.setObjectName(_fromUtf8("startLat"))
        self.gridLayout.addWidget(self.startLat, 0, 1, 1, 1)
        self.startLon = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.startLon.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.startLon.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startLon.setKeyboardTracking(True)
        self.startLon.setDecimals(6)
        self.startLon.setMinimum(-99999999.0)
        self.startLon.setMaximum(99999999.0)
        self.startLon.setObjectName(_fromUtf8("startLon"))
        self.gridLayout.addWidget(self.startLon, 1, 1, 1, 1)
        self.finalLat = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.finalLat.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.finalLat.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.finalLat.setKeyboardTracking(True)
        self.finalLat.setDecimals(6)
        self.finalLat.setMinimum(-99999999.0)
        self.finalLat.setMaximum(99999999.0)
        self.finalLat.setObjectName(_fromUtf8("finalLat"))
        self.gridLayout.addWidget(self.finalLat, 2, 1, 1, 1)
        self.finalLon = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.finalLon.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.finalLon.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.finalLon.setKeyboardTracking(True)
        self.finalLon.setDecimals(6)
        self.finalLon.setMinimum(-99999999.0)
        self.finalLon.setMaximum(99999999.0)
        self.finalLon.setObjectName(_fromUtf8("finalLon"))
        self.gridLayout.addWidget(self.finalLon, 3, 1, 1, 1)
        self.autoTransectCheck = QtGui.QCheckBox(self.groupBox_2)
        self.autoTransectCheck.setGeometry(QtCore.QRect(20, 27, 175, 21))
        self.autoTransectCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.autoTransectCheck.setChecked(True)
        self.autoTransectCheck.setObjectName(_fromUtf8("autoTransectCheck"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(210, 20, 40, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_3 = QtGui.QGroupBox(transectizer)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 271, 141))
        self.groupBox_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 251, 100))
        self.layoutWidget3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.outputToExisting = QtGui.QRadioButton(self.layoutWidget3)
        self.outputToExisting.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.outputToExisting.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputToExisting.setChecked(True)
        self.outputToExisting.setObjectName(_fromUtf8("outputToExisting"))
        self.gridLayout_2.addWidget(self.outputToExisting, 0, 0, 1, 2)
        self.outputToNew = QtGui.QRadioButton(self.layoutWidget3)
        self.outputToNew.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.outputToNew.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputToNew.setObjectName(_fromUtf8("outputToNew"))
        self.gridLayout_2.addWidget(self.outputToNew, 2, 0, 1, 2)
        self.newLayerLabel = QtGui.QLabel(self.layoutWidget3)
        self.newLayerLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.newLayerLabel.setObjectName(_fromUtf8("newLayerLabel"))
        self.gridLayout_2.addWidget(self.newLayerLabel, 3, 0, 1, 1)
        self.newLayerName = QtGui.QLineEdit(self.layoutWidget3)
        self.newLayerName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.newLayerName.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.newLayerName.setObjectName(_fromUtf8("newLayerName"))
        self.gridLayout_2.addWidget(self.newLayerName, 3, 1, 1, 1)
        self.layersCombo = QtGui.QComboBox(self.layoutWidget3)
        self.layersCombo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.layersCombo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.layersCombo.setObjectName(_fromUtf8("layersCombo"))
        self.gridLayout_2.addWidget(self.layersCombo, 1, 0, 1, 2)
        self.doneButton = QtGui.QPushButton(transectizer)
        self.doneButton.setGeometry(QtCore.QRect(30, 580, 99, 20))
        self.doneButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doneButton.setAutoDefault(False)
        self.doneButton.setObjectName(_fromUtf8("doneButton"))
        self.aboutButton = QtGui.QPushButton(transectizer)
        self.aboutButton.setGeometry(QtCore.QRect(140, 580, 99, 20))
        self.aboutButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.aboutButton.setAutoDefault(False)
        self.aboutButton.setFlat(False)
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.stnPreLabel.setBuddy(self.stationPrefix)
        self.iniNumLabel.setBuddy(self.initialStationNumber)
        self.srvNameLabel.setBuddy(self.surveyName)
        self.dstBtwnStLabel.setBuddy(self.dstBtwnStations)
        self.dstBtwnStLabel_2.setBuddy(self.unitsCombo)
        self.numberOfStationsLabel.setBuddy(self.numberOfStations)
        self.bearingLabel.setBuddy(self.bearing)
        self.startLonLabel.setBuddy(self.startLon)
        self.finalLonLabel.setBuddy(self.finalLon)
        self.StartLatLAbel.setBuddy(self.startLat)
        self.finalLatLabel.setBuddy(self.finalLat)
        self.newLayerLabel.setBuddy(self.newLayerName)

        self.retranslateUi(transectizer)
        QtCore.QObject.connect(self.doneButton, QtCore.SIGNAL(_fromUtf8("clicked()")), transectizer.accept)
        QtCore.QObject.connect(self.startLat, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.startLon.setFocus)
        QtCore.QObject.connect(self.startLon, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.finalLat.setFocus)
        QtCore.QObject.connect(self.finalLat, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.finalLon.setFocus)
        QtCore.QObject.connect(self.finalLon, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.dstBtwnStations.setFocus)
        QtCore.QObject.connect(self.dstBtwnStations, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.unitsCombo.setFocus)
        QtCore.QObject.connect(self.bearing, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.dstBtwnStations.setFocus)
        QtCore.QObject.connect(self.surveyName, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.stationPrefix.setFocus)
        QtCore.QObject.connect(self.stationPrefix, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.initialStationNumber.setFocus)
        QtCore.QObject.connect(self.initialStationNumber, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.newTransectButton.setFocus)
        QtCore.QObject.connect(self.numberOfStations, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.surveyName.setFocus)
        QtCore.QMetaObject.connectSlotsByName(transectizer)
        transectizer.setTabOrder(self.startLat, self.startLon)
        transectizer.setTabOrder(self.startLon, self.finalLat)
        transectizer.setTabOrder(self.finalLat, self.finalLon)
        transectizer.setTabOrder(self.finalLon, self.bearing)
        transectizer.setTabOrder(self.bearing, self.dstBtwnStations)
        transectizer.setTabOrder(self.dstBtwnStations, self.unitsCombo)
        transectizer.setTabOrder(self.unitsCombo, self.numberOfStations)
        transectizer.setTabOrder(self.numberOfStations, self.autoNameCheck)
        transectizer.setTabOrder(self.autoNameCheck, self.surveyName)
        transectizer.setTabOrder(self.surveyName, self.stationPrefix)
        transectizer.setTabOrder(self.stationPrefix, self.initialStationNumber)
        transectizer.setTabOrder(self.initialStationNumber, self.newTransectButton)
        transectizer.setTabOrder(self.newTransectButton, self.doneButton)
        transectizer.setTabOrder(self.doneButton, self.newLayerName)
        transectizer.setTabOrder(self.newLayerName, self.layersCombo)
        transectizer.setTabOrder(self.layersCombo, self.outputToExisting)
        transectizer.setTabOrder(self.outputToExisting, self.outputToNew)
        transectizer.setTabOrder(self.outputToNew, self.autoTransectCheck)

    def retranslateUi(self, transectizer):
        transectizer.setWindowTitle(_translate("transectizer", "Transectizer", None))
        self.groupBox.setTitle(_translate("transectizer", "Stations details", None))
        self.surveyName.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the value for the field <span style=\" font-style:italic;\">survey</span> of your transectizer layer.</p></body></html>", None))
        self.surveyName.setText(_translate("transectizer", "MySurvey", None))
        self.stnPreLabel.setText(_translate("transectizer", "Station Prefix", None))
        self.iniNumLabel.setText(_translate("transectizer", "Initial Station Number", None))
        self.stationPrefix.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the value for the field <span style=\" font-style:italic;\">station</span> of your transectizer layer.</p></body></html>", None))
        self.stationPrefix.setText(_translate("transectizer", "St", None))
        self.autoNameCheck.setToolTip(_translate("transectizer", "<html><head/><body><p><span style=\" font-weight:600;\">With Automatic Station Details,</span> Transectizer will fill up the fields describing the stations for you with the parameters below. </p><p><span style=\" font-weight:600;\">Without Automatic Station Details,</span> you will be prompted for survey name, station prefix, station number and observations <span style=\" font-style:italic; text-decoration: underline;\">for each deployed station.</span> Bear in mind that, in case of a high number of stations, it can be tedious.</p></body></html>", None))
        self.autoNameCheck.setText(_translate("transectizer", "Automatic Station details", None))
        self.initialStationNumber.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here an <span style=\" font-style:italic;\">offset for the station number</span> of your layer, in case you don\'t want it to start from one.</p></body></html>", None))
        self.srvNameLabel.setText(_translate("transectizer", "Survey/Transect Name", None))
        self.newTransectButton.setToolTip(_translate("transectizer", "<html><head/><body><p>Press this button to for Transectizer do do its work,</p></body></html>", None))
        self.newTransectButton.setText(_translate("transectizer", "Create new transect", None))
        self.groupBox_2.setTitle(_translate("transectizer", "Transect definition", None))
        self.unitsCombo.setToolTip(_translate("transectizer", "<html><head/><body><p>Select the measurement units for the distance between stations.</p></body></html>", None))
        self.unitsCombo.setItemText(0, _translate("transectizer", "Meters", None))
        self.unitsCombo.setItemText(1, _translate("transectizer", "Kilometers", None))
        self.unitsCombo.setItemText(2, _translate("transectizer", "Feet", None))
        self.unitsCombo.setItemText(3, _translate("transectizer", "Yards", None))
        self.unitsCombo.setItemText(4, _translate("transectizer", "Miles", None))
        self.unitsCombo.setItemText(5, _translate("transectizer", "Nautical miles", None))
        self.dstBtwnStLabel.setText(_translate("transectizer", "Station distance", None))
        self.dstBtwnStLabel_2.setText(_translate("transectizer", "Distance units", None))
        self.numberOfStationsLabel.setText(_translate("transectizer", "Number of stations", None))
        self.bearingLabel.setText(_translate("transectizer", "Bearing (degrees)", None))
        self.numberOfStations.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the number of stations to be deployed along the transect.</p></body></html>", None))
        self.dstBtwnStations.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the distance between stations in the units selected below.</p></body></html>", None))
        self.bearing.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the bearing of the transect in degrees.</p></body></html>", None))
        self.startLonLabel.setText(_translate("transectizer", "Initial longitude", None))
        self.finalLonLabel.setText(_translate("transectizer", "Final longitude", None))
        self.StartLatLAbel.setText(_translate("transectizer", "Initial latitude", None))
        self.finalLatLabel.setText(_translate("transectizer", "Final latitude", None))
        self.startLat.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the latitude of the initial point of the transect. <span style=\" font-weight:600;\">Remember to provide it in the same CRS than your project.</span></p></body></html>", None))
        self.startLon.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the longitude of the initial point of the transect. <span style=\" font-weight:600;\">Remember to provide it in the same CRS than your project.</span></p></body></html>", None))
        self.finalLat.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the latitude of the final point of a line defining the transect. <span style=\" font-weight:600;\">Remember to provide it in the same CRS than your project.</span></p></body></html>", None))
        self.finalLon.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the longitude of the final point of a line defining the transect. r<span style=\" font-weight:600;\">emember to provide it in the same CRS than your project.</span></p></body></html>", None))
        self.autoTransectCheck.setToolTip(_translate("transectizer", "<html><head/><body><p><span style=\" font-weight:600;\">With automatic transect definition,</span> you can press left mouse button, drag and release left button on the canvas to define the initial point and bearing of your transect.</p><p><span style=\" font-weight:600;\">With manual transect definition</span>, you must provide at least the initial point of your transect and its bearing, or both initial and ending points defining the transect line to get the bearing calculated for you. <span style=\" font-weight:600; font-style:italic; color:#ff0000;\">You must provide the coordinates in your</span><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#ff0000;\"> Project</span><span style=\" font-weight:600; font-style:italic; color:#ff0000;\"> CRS.</span></p></body></html>", None))
        self.autoTransectCheck.setText(_translate("transectizer", "Automatic (pick from map)", None))
        self.pushButton.setText(_translate("transectizer", "GPS", None))
        self.groupBox_3.setTitle(_translate("transectizer", "Destination layer", None))
        self.outputToExisting.setToolTip(_translate("transectizer", "<html><head/><body><p>Select this option to choose an existing layer from the combobox below. Transectizer will check if the selected layer has all the attributes for transectizer to work. You can find details about this in the help.</p></body></html>", None))
        self.outputToExisting.setText(_translate("transectizer", "Choose an existing layer", None))
        self.outputToNew.setToolTip(_translate("transectizer", "<html><head/><body><p>Select this option to create a new memory layer. The new layer will be created with WGS84 (EPSG 4326) as CRS.</p><p><span style=\" font-weight:600; color:#ff0000;\">Don\'t forget to save it before closing your project!!!</span></p></body></html>", None))
        self.outputToNew.setText(_translate("transectizer", "Create new (must save later)", None))
        self.newLayerLabel.setText(_translate("transectizer", "Layer name", None))
        self.newLayerName.setToolTip(_translate("transectizer", "<html><head/><body><p>Type here the name of your new layer</p></body></html>", None))
        self.newLayerName.setText(_translate("transectizer", "MyTransect", None))
        self.doneButton.setText(_translate("transectizer", "Done", None))
        self.aboutButton.setText(_translate("transectizer", "About/Help", None))

